### ISSUE TITLE
The sharing pretrained imagenet model in GoogleDrive cannot be decompressed.

### ISSUE THREAD

**Issue by czp97** [sharling-lz/ppnet#1]
Hello. Thanks for your code. I have a problem that the sharing pretrained imagenet model in GoogleDrive cannot be decompressed. It warns data corruption. Can you reload the model or give ohter link like BaiduDisk?
Thanks very much!

**Comment by sharling-lz** [comment]
The model files are not needed to be decompressed, just directly load the model file.

**Comment by czp97** [comment]
Thanks for your reply.  Sorry, I have not noticed that the pretrained model file in experiment config is a tar file.
